import type {CompleteArgs} from '../llm/anthropic.js'

// A checklist is a quality gate authored FOR a spec: "is this spec ready?".
// The base items are fixed (every spec is held to them); the LLM may append
// spec-specific items. Completeness ([x] everywhere) can gate Approval.
const BASE_ITEMS = [
  'Objective is a single, testable sentence',
  'Scope explicitly lists what is OUT of scope',
  'Every functional requirement (FR-n) is unambiguous',
  'Every acceptance criterion (AC-n) is Given/When/Then and linked to a test',
  'No remaining [NEEDS CLARIFICATION] markers',
  'API/contract deltas are backward-compatible (or migration is described)',
  'Security deltas (scopes/ownership) are stated, not assumed',
  'Persistence and eventing changes follow the base-spec rules',
  'Observability for new endpoints/consumers is specified',
  'Base-spec amendments (if any) are listed in section 14',
]

export function checklistSkeleton(specTitle: string, extraItems: string[]): string {
  const items = [...BASE_ITEMS, ...extraItems]
    .map((i) => `- [ ] ${i}`)
    .join('\n')
  return `# Spec Quality Checklist: ${specTitle}

> Generated by \`speccord checklist\`. The spec is "ready" when every box is checked.
> \`speccord analyze\` and the Approval gate read this file.

${items}
`
}

// True when every checkbox in the checklist body is checked.
export function checklistComplete(text: string): boolean {
  const boxes = [...text.matchAll(/^\s*- \[( |x|X)\]/gm)]
  return boxes.length > 0 && boxes.every((m) => m[1].toLowerCase() === 'x')
}

export function buildChecklistPrompt(args: {specTitle: string; specBody: string}): CompleteArgs {
  return {
    maxTokens: 600,
    system:
      'You add spec-SPECIFIC quality-checklist items for a feature spec, beyond the standard ones ' +
      'already covered (clarity, scope, testable ACs, backward-compat, security, observability). ' +
      'Focus on risks unique to THIS spec (tricky edge cases, data migrations, concurrency). ' +
      'Output a plain bullet list of short imperative checks — no numbering, no preamble. Max 6.',
    user: `Feature spec:\n# ${args.specTitle}\n${args.specBody}`,
  }
}

// Parse an LLM bullet list into clean item strings.
export function parseExtraItems(text: string): string[] {
  return text
    .split('\n')
    .map((l) => l.replace(/^\s*[-*]\s*/, '').replace(/^\[\s*\]\s*/, '').trim())
    .filter(Boolean)
    .slice(0, 6)
}
