import type {CompleteArgs} from '../llm/anthropic.js'

// The deterministic skeleton of a plan. The LLM fills the prose; the headings,
// the "Constitution check" gate, and the structure are fixed by speccord.
export function planSkeleton(specTitle: string, body: string): string {
  return `# Implementation Plan: ${specTitle}

> Generated by \`speccord plan\` from the approved feature spec.
> The spec says WHAT and WHY; this plan says HOW. Tasks are derived from it.

${body}
`
}

const PLAN_SECTIONS = `Produce these sections as GitHub-flavored Markdown:

## 1. Technical approach
How the change is implemented at a high level, in terms of the existing service.

## 2. Architecture & components touched
Which modules/layers/files change, and the responsibility of each.

## 3. Constitution check
For each relevant principle (P-n) from the constitution, state how the plan
honors it. If any principle is violated, record an explicit exception and why.

## 4. Data & contract changes
Schema/migration deltas and OpenAPI/event-contract deltas. Backward-compat notes.

## 5. Sequencing & risk
The order work must happen in, dependencies, and the riskiest steps with mitigations.

## 6. Test strategy
How each acceptance criterion (AC-n) will be verified, mapped to test types.`

// Deterministic placeholder used when the LLM is disabled.
export function planPlaceholder(): string {
  return PLAN_SECTIONS.replace(
    /^(##.*)$/gm,
    '$1\n<!-- TODO: draft (no LLM). Set ANTHROPIC_API_KEY + use --llm to auto-draft. -->',
  )
}

export function buildPlanPrompt(args: {
  specTitle: string
  specBody: string
  baseSpec: string
  constitution: string
}): CompleteArgs {
  return {
    maxTokens: 2000,
    system:
      'You are a senior engineer writing an implementation plan for a change to an EXISTING ' +
      'Spring Boot microservice. Ground every decision in the provided base spec (the service ' +
      'contract) and constitution (non-negotiable principles). Do NOT invent endpoints, tables, ' +
      'topics, or scopes that are not in the inputs. Keep it concrete and reviewable. ' +
      'Output only the requested Markdown sections — no preamble.',
    user:
      `## Constitution\n${args.constitution}\n\n` +
      `## Base service spec (the contract)\n${args.baseSpec}\n\n` +
      `## Feature spec to plan\n# ${args.specTitle}\n${args.specBody}\n\n` +
      `---\n${PLAN_SECTIONS}`,
  }
}
