import type {CompleteArgs} from '../llm/anthropic.js'
import type {TaskItem} from './model.js'

// Canonical task line:  - [ ] T-1 [P] Title (files: a.java, b.java) [AC: AC-1, AC-2]
// [P] marks a task that can run in parallel with its siblings.
const TASK_RE = /^\s*- \[( |x|X)\]\s*(T-\d+)\s*(\[P\])?\s*(.*?)\s*$/

function extractFiles(title: string): {title: string; files: string[]} {
  const m = title.match(/\(files:\s*([^)]*)\)/i)
  if (!m) return {title: title.trim(), files: []}
  const files = m[1].split(',').map((s) => s.trim()).filter(Boolean)
  return {title: title.replace(m[0], '').trim(), files}
}

export function parseTasks(text: string): TaskItem[] {
  const tasks: TaskItem[] = []
  for (const line of text.split('\n')) {
    const m = line.match(TASK_RE)
    if (!m) continue
    const {title, files} = extractFiles(m[4] ?? '')
    tasks.push({
      id: m[2],
      done: m[1].toLowerCase() === 'x',
      parallel: Boolean(m[3]),
      title,
      files,
    })
  }
  return tasks
}

// Rewrite the checkbox for a given task id in place, preserving everything else.
export function setTaskDone(text: string, id: string, done: boolean): string {
  return text
    .split('\n')
    .map((line) => {
      const m = line.match(TASK_RE)
      if (!m || m[2] !== id) return line
      return line.replace(/\[( |x|X)\]/, done ? '[x]' : '[ ]')
    })
    .join('\n')
}

export function tasksSkeleton(specTitle: string, body: string): string {
  return `# Tasks: ${specTitle}

> Generated by \`speccord tasks\` from the plan. Ordered. \`[P]\` = parallelizable.
> Check a box (or run \`speccord implement\`) as each task completes.

${body}
`
}

const TASK_RULES = `Break the plan into an ORDERED, dependency-aware checklist of small tasks.
Rules:
- One line per task: "- [ ] T-1 Title (files: path) [AC: AC-n]".
- Number them T-1, T-2, ... in execution order.
- Mark tasks that can run in parallel with "[P]" right after the id.
- Reference the acceptance criteria each task helps satisfy as "[AC: AC-1, ...]".
- Put real target file paths in "(files: ...)" when known from the plan.
- Cover EVERY acceptance criterion; the last tasks should wire up and verify tests.
- Output only the checklist lines under a single "## Tasks" heading — no prose.`

export function tasksPlaceholder(): string {
  return `## Tasks
<!-- TODO: derive tasks from the plan (no LLM). Use --llm to auto-generate. -->
- [ ] T-1 (files: ) [AC: ]
`
}

export function buildTasksPrompt(args: {
  specTitle: string
  specBody: string
  planText: string
}): CompleteArgs {
  return {
    maxTokens: 1800,
    system:
      'You convert an implementation plan into a concrete, ordered task checklist for an ' +
      'existing Spring Boot microservice. Be exhaustive but minimal — no task without a purpose. ' +
      'Do not invent scope beyond the plan and spec.',
    user:
      `## Feature spec\n# ${args.specTitle}\n${args.specBody}\n\n` +
      `## Implementation plan\n${args.planText}\n\n---\n${TASK_RULES}`,
  }
}
